clear
close all
wp=0.12*pi;
ws=0.18*pi;
A=30;
[w,N]=kwin(ws-wp,A);
n=0:N-1;
wc=0.15*pi;
alpha=(N-1)/2;
h=firlp(N,wc).*w;
delta=+(n==alpha);
hHP=delta-h; % transform lowpass to highpass with the same cutoff frequency
figure
subplot(2,1,1)
stem(n,hHP)
xlabel('n')
ylabel('h(n)')
xlim([-1,53])
subplot(2,1,2)
dtft(hHP);
xlim([0,1])

w0=0.25*pi;
deltaw=0.3*pi;
wcL=w0-deltaw/2;
wcH=w0+deltaw/2;
hLP1=firlp(N,wcL).*w;
hLP2=firlp(N,wcH).*w;
hHP2=delta-hLP2;
hBP=delta-(hHP2+hLP1);
%hdBP=2*sin(deltaw/2*n)/(pi*n)*cos(w0*n);
figure
subplot(2,1,1)
stem(n,hBP)
xlabel('n')
ylabel('h(n)')
xlim([-1,53])
subplot(2,1,2)
dtft(hBP);
xlim([0,1])